services:
  hairlab-api:
    build: .
    container_name: hairlab-api
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_hairlab
      - SPRING_DATASOURCE_USERNAME=hairlab_root
      - SPRING_DATASOURCE_PASSWORD=hairlab123!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VIRTUAL_PORT=8080
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=db_hairlab
      - POSTGRES_USER=hairlab_root
      - POSTGRES_PASSWORD=hairlab123!
    ports:
      - "5432:5432"
